package com.unicornsummer.mybatis.generator.example.entity;

public class User extends UserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Password
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Select_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String selectPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Insert_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String insertPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Update_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String updatePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Delete_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String deletePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String createPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Drop_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String dropPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Reload_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String reloadPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Shutdown_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String shutdownPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Process_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String processPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.File_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String filePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Grant_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String grantPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.References_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String referencesPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Index_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String indexPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Alter_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String alterPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Show_db_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String showDbPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Super_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String superPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_tmp_table_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String createTmpTablePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Lock_tables_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String lockTablesPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Execute_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String executePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Repl_slave_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String replSlavePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Repl_client_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String replClientPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_view_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String createViewPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Show_view_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String showViewPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_routine_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String createRoutinePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Alter_routine_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String alterRoutinePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_user_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String createUserPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Event_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String eventPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Trigger_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String triggerPriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.Create_tablespace_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String createTablespacePriv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ssl_type
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String sslType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_questions
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private Integer maxQuestions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_updates
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private Integer maxUpdates;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_connections
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private Integer maxConnections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.max_user_connections
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private Integer maxUserConnections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.plugin
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String plugin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password_expired
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    private String passwordExpired;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Password
     *
     * @return the value of user.Password
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Password
     *
     * @param password the value for user.Password
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Select_priv
     *
     * @return the value of user.Select_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getSelectPriv() {
        return selectPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Select_priv
     *
     * @param selectPriv the value for user.Select_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setSelectPriv(String selectPriv) {
        this.selectPriv = selectPriv == null ? null : selectPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Insert_priv
     *
     * @return the value of user.Insert_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getInsertPriv() {
        return insertPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Insert_priv
     *
     * @param insertPriv the value for user.Insert_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setInsertPriv(String insertPriv) {
        this.insertPriv = insertPriv == null ? null : insertPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Update_priv
     *
     * @return the value of user.Update_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getUpdatePriv() {
        return updatePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Update_priv
     *
     * @param updatePriv the value for user.Update_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setUpdatePriv(String updatePriv) {
        this.updatePriv = updatePriv == null ? null : updatePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Delete_priv
     *
     * @return the value of user.Delete_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getDeletePriv() {
        return deletePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Delete_priv
     *
     * @param deletePriv the value for user.Delete_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setDeletePriv(String deletePriv) {
        this.deletePriv = deletePriv == null ? null : deletePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_priv
     *
     * @return the value of user.Create_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getCreatePriv() {
        return createPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_priv
     *
     * @param createPriv the value for user.Create_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setCreatePriv(String createPriv) {
        this.createPriv = createPriv == null ? null : createPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Drop_priv
     *
     * @return the value of user.Drop_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getDropPriv() {
        return dropPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Drop_priv
     *
     * @param dropPriv the value for user.Drop_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setDropPriv(String dropPriv) {
        this.dropPriv = dropPriv == null ? null : dropPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Reload_priv
     *
     * @return the value of user.Reload_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getReloadPriv() {
        return reloadPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Reload_priv
     *
     * @param reloadPriv the value for user.Reload_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setReloadPriv(String reloadPriv) {
        this.reloadPriv = reloadPriv == null ? null : reloadPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Shutdown_priv
     *
     * @return the value of user.Shutdown_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getShutdownPriv() {
        return shutdownPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Shutdown_priv
     *
     * @param shutdownPriv the value for user.Shutdown_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setShutdownPriv(String shutdownPriv) {
        this.shutdownPriv = shutdownPriv == null ? null : shutdownPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Process_priv
     *
     * @return the value of user.Process_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getProcessPriv() {
        return processPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Process_priv
     *
     * @param processPriv the value for user.Process_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setProcessPriv(String processPriv) {
        this.processPriv = processPriv == null ? null : processPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.File_priv
     *
     * @return the value of user.File_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getFilePriv() {
        return filePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.File_priv
     *
     * @param filePriv the value for user.File_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setFilePriv(String filePriv) {
        this.filePriv = filePriv == null ? null : filePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Grant_priv
     *
     * @return the value of user.Grant_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getGrantPriv() {
        return grantPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Grant_priv
     *
     * @param grantPriv the value for user.Grant_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setGrantPriv(String grantPriv) {
        this.grantPriv = grantPriv == null ? null : grantPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.References_priv
     *
     * @return the value of user.References_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getReferencesPriv() {
        return referencesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.References_priv
     *
     * @param referencesPriv the value for user.References_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setReferencesPriv(String referencesPriv) {
        this.referencesPriv = referencesPriv == null ? null : referencesPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Index_priv
     *
     * @return the value of user.Index_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getIndexPriv() {
        return indexPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Index_priv
     *
     * @param indexPriv the value for user.Index_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setIndexPriv(String indexPriv) {
        this.indexPriv = indexPriv == null ? null : indexPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Alter_priv
     *
     * @return the value of user.Alter_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getAlterPriv() {
        return alterPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Alter_priv
     *
     * @param alterPriv the value for user.Alter_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setAlterPriv(String alterPriv) {
        this.alterPriv = alterPriv == null ? null : alterPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Show_db_priv
     *
     * @return the value of user.Show_db_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getShowDbPriv() {
        return showDbPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Show_db_priv
     *
     * @param showDbPriv the value for user.Show_db_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setShowDbPriv(String showDbPriv) {
        this.showDbPriv = showDbPriv == null ? null : showDbPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Super_priv
     *
     * @return the value of user.Super_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getSuperPriv() {
        return superPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Super_priv
     *
     * @param superPriv the value for user.Super_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setSuperPriv(String superPriv) {
        this.superPriv = superPriv == null ? null : superPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_tmp_table_priv
     *
     * @return the value of user.Create_tmp_table_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getCreateTmpTablePriv() {
        return createTmpTablePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_tmp_table_priv
     *
     * @param createTmpTablePriv the value for user.Create_tmp_table_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setCreateTmpTablePriv(String createTmpTablePriv) {
        this.createTmpTablePriv = createTmpTablePriv == null ? null : createTmpTablePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Lock_tables_priv
     *
     * @return the value of user.Lock_tables_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getLockTablesPriv() {
        return lockTablesPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Lock_tables_priv
     *
     * @param lockTablesPriv the value for user.Lock_tables_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setLockTablesPriv(String lockTablesPriv) {
        this.lockTablesPriv = lockTablesPriv == null ? null : lockTablesPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Execute_priv
     *
     * @return the value of user.Execute_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getExecutePriv() {
        return executePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Execute_priv
     *
     * @param executePriv the value for user.Execute_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setExecutePriv(String executePriv) {
        this.executePriv = executePriv == null ? null : executePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Repl_slave_priv
     *
     * @return the value of user.Repl_slave_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getReplSlavePriv() {
        return replSlavePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Repl_slave_priv
     *
     * @param replSlavePriv the value for user.Repl_slave_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setReplSlavePriv(String replSlavePriv) {
        this.replSlavePriv = replSlavePriv == null ? null : replSlavePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Repl_client_priv
     *
     * @return the value of user.Repl_client_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getReplClientPriv() {
        return replClientPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Repl_client_priv
     *
     * @param replClientPriv the value for user.Repl_client_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setReplClientPriv(String replClientPriv) {
        this.replClientPriv = replClientPriv == null ? null : replClientPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_view_priv
     *
     * @return the value of user.Create_view_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getCreateViewPriv() {
        return createViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_view_priv
     *
     * @param createViewPriv the value for user.Create_view_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setCreateViewPriv(String createViewPriv) {
        this.createViewPriv = createViewPriv == null ? null : createViewPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Show_view_priv
     *
     * @return the value of user.Show_view_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getShowViewPriv() {
        return showViewPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Show_view_priv
     *
     * @param showViewPriv the value for user.Show_view_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setShowViewPriv(String showViewPriv) {
        this.showViewPriv = showViewPriv == null ? null : showViewPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_routine_priv
     *
     * @return the value of user.Create_routine_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getCreateRoutinePriv() {
        return createRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_routine_priv
     *
     * @param createRoutinePriv the value for user.Create_routine_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setCreateRoutinePriv(String createRoutinePriv) {
        this.createRoutinePriv = createRoutinePriv == null ? null : createRoutinePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Alter_routine_priv
     *
     * @return the value of user.Alter_routine_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getAlterRoutinePriv() {
        return alterRoutinePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Alter_routine_priv
     *
     * @param alterRoutinePriv the value for user.Alter_routine_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setAlterRoutinePriv(String alterRoutinePriv) {
        this.alterRoutinePriv = alterRoutinePriv == null ? null : alterRoutinePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_user_priv
     *
     * @return the value of user.Create_user_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getCreateUserPriv() {
        return createUserPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_user_priv
     *
     * @param createUserPriv the value for user.Create_user_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setCreateUserPriv(String createUserPriv) {
        this.createUserPriv = createUserPriv == null ? null : createUserPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Event_priv
     *
     * @return the value of user.Event_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getEventPriv() {
        return eventPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Event_priv
     *
     * @param eventPriv the value for user.Event_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setEventPriv(String eventPriv) {
        this.eventPriv = eventPriv == null ? null : eventPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Trigger_priv
     *
     * @return the value of user.Trigger_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getTriggerPriv() {
        return triggerPriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Trigger_priv
     *
     * @param triggerPriv the value for user.Trigger_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setTriggerPriv(String triggerPriv) {
        this.triggerPriv = triggerPriv == null ? null : triggerPriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.Create_tablespace_priv
     *
     * @return the value of user.Create_tablespace_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getCreateTablespacePriv() {
        return createTablespacePriv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.Create_tablespace_priv
     *
     * @param createTablespacePriv the value for user.Create_tablespace_priv
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setCreateTablespacePriv(String createTablespacePriv) {
        this.createTablespacePriv = createTablespacePriv == null ? null : createTablespacePriv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ssl_type
     *
     * @return the value of user.ssl_type
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getSslType() {
        return sslType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ssl_type
     *
     * @param sslType the value for user.ssl_type
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setSslType(String sslType) {
        this.sslType = sslType == null ? null : sslType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_questions
     *
     * @return the value of user.max_questions
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public Integer getMaxQuestions() {
        return maxQuestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_questions
     *
     * @param maxQuestions the value for user.max_questions
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setMaxQuestions(Integer maxQuestions) {
        this.maxQuestions = maxQuestions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_updates
     *
     * @return the value of user.max_updates
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public Integer getMaxUpdates() {
        return maxUpdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_updates
     *
     * @param maxUpdates the value for user.max_updates
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setMaxUpdates(Integer maxUpdates) {
        this.maxUpdates = maxUpdates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_connections
     *
     * @return the value of user.max_connections
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public Integer getMaxConnections() {
        return maxConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_connections
     *
     * @param maxConnections the value for user.max_connections
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setMaxConnections(Integer maxConnections) {
        this.maxConnections = maxConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.max_user_connections
     *
     * @return the value of user.max_user_connections
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public Integer getMaxUserConnections() {
        return maxUserConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.max_user_connections
     *
     * @param maxUserConnections the value for user.max_user_connections
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setMaxUserConnections(Integer maxUserConnections) {
        this.maxUserConnections = maxUserConnections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.plugin
     *
     * @return the value of user.plugin
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getPlugin() {
        return plugin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.plugin
     *
     * @param plugin the value for user.plugin
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setPlugin(String plugin) {
        this.plugin = plugin == null ? null : plugin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password_expired
     *
     * @return the value of user.password_expired
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public String getPasswordExpired() {
        return passwordExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password_expired
     *
     * @param passwordExpired the value for user.password_expired
     *
     * @mbggenerated Wed Oct 21 23:54:49 CST 2015
     */
    public void setPasswordExpired(String passwordExpired) {
        this.passwordExpired = passwordExpired == null ? null : passwordExpired.trim();
    }
}